---
label: Site Config
hide_body: false
fields:
- name: title
  label: Nombre del negocio
  type: text
  hidden: false
  default: ''
- name: description
  label: Descripción del negocio
  type: text
  hidden: false
  default: ''
- type: file
  name: logo
  label: Logo
- name: copy
  label: Texto Copywright
  type: text
  hidden: false
  default: ''
- name: footer_frase
  label: Frase Footer
  type: text
  hidden: false
  default: ''
- name: favicon
  label: Favicon
  type: file
  hidden: false
  default: ''
- name: phones
  label: Teléfonos
  type: field_group_list
  fields:
  - name: visible
    label: Teléfono
    type: text
    hidden: false
    default: ''
  - name: link
    label: Teléfono (Sin Espacios)
    type: text
    hidden: false
    default: ''
- name: fax
  label: Fax
  type: text
  hidden: false
  default: ''
- name: email
  label: Email
  type: text
  hidden: false
  default: ''
- name: social_media
  type: field_group
  config: {}
  fields:
  - name: facebook
    type: text
    config:
      required: false
    label: Facebook
  - name: twitter
    type: text
    config:
      required: false
    label: Twitter
  - name: instagram
    type: text
    config:
      required: false
    label: Instagram
  label: Redes Sociales
- name: address
  label: Dirección
  type: field_group
  fields:
  - name: street
    label: Dirección (linea 1)
    type: text
  - name: street2
    label: Dirección (linea 2)
    type: text
  - name: postalCode
    label: Código Postal
    type: text
  - name: city
    label: Ciudad
    type: text
- name: transports
  type: field_group_list
  fields:
  - name: transport_label
    type: text
    config:
      required: false
    label: Tipo de transporte
  - name: transport_text
    type: text
    config:
      required: false
    label: Descripción
  config:
    min: 
    max: 
    labelField: 
  label: Cómo Llegar
- name: schedule
  type: field_group
  config: {}
  fields:
  - name: schedule_long
    type: field_group_list
    fields:
    - name: item
      type: text
      config:
        required: false
      label: Elemento
    config:
      min: 
      max: 
      labelField: 
    label: Horarios versión larga
    description: Lista de horarios en los que escribimos los días con su texto completo
      (Lunes, Martes...)
  - name: schedule_short
    type: field_group_list
    fields:
    - name: item
      type: text
      config:
        required: false
      label: Elemento
    config:
      min: 
      max: 
      labelField: 
    label: Horarios Versión Abreviada
    description: Versión abreviada de los horarios (pe. L-V 12-14h)
  label: Horarios
  description: Horarios del negocio
- name: navigation
  label: Navigation
  type: field_group_list
  fields:
  - name: text
    label: Text
    type: text
    hidden: false
    default: ''
  - name: link
    label: Link
    type: text
    hidden: false
    default: ''
  - name: external
    label: External
    type: boolean
    hidden: false
    default: ''
  hidden: false
  default: ''
- name: footer_navigation
  label: Footer Navigation
  type: field_group_list
  fields:
  - name: text
    label: Text
    type: text
    hidden: false
    default: ''
  - name: link
    label: Link
    type: text
    hidden: false
    default: ''
  - name: external
    label: External
    type: boolean
    hidden: false
    default: ''
  hidden: false
  default: ''
- name: notice
  type: field_group
  config: {}
  fields:
  - name: notice_title
    type: text
    config:
      required: false
    label: Título
  - name: notice_text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html
    label: Texto
  - name: notice_btn_text
    type: text
    config:
      required: false
    label: Texto Botón
  - name: notice_btn_link
    type: text
    config:
      required: false
    label: Enlace Botón
  label: Aviso
pages:
- portfolio/config.json
